server:
  port: 8091
spring:
  application:
    name: springboot-mybatis
  datasource:
    #主数据源
    mysql:
      db1:
        url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai&autoReconnect=true&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=true&usePublicRetrieve=true
        username: root
        password: Wcy539976
        driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #连接池设置
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # Oracle请使用select 1 from dual
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
    clickhouse:
      driverClassName: com.clickhouse.jdbc.ClickHouseDriver
      url: jdbc:clickhouse://127.0.0.1:8123/default
      username: chance
      password: Wcy539976
      initialSize: 10
      maxActive: 100
      minIdle: 10
      maxWait: 6000

  batch:
    initialize-schema: always # 项目启动时执行建表sql
    job:
      enabled: false # 禁止自动执行，需手动触发

  messages:
    basename: i18n/messages
    encoding: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # redis
  redis:
    host: localhost
    port: 6379
    database: 1
    timeout: 7200s
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-wait: -1
        max-active: -1

#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
#    virtual-host: vhost

#######################tk mybatis##########################
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#    use-generated-keys: true
#  type-aliases-package: com.chance.entity
#  mapper-locations: classpath*:/mapper/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments:
  params: count=countSql
########################################################

####################### mybatis-plus ##########################
#mybatis-plus:
#  type-aliases-package: com.chance.entity
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  type-handlers-package: com.chance.entity.typehandler

#logging:
#  level:
#    com:
#      chance:
#        mapper: debug

#########################################################

jwt:
  expire: 3600

file:
  save-path: /Users/chenyang/Desktop/

skywalking:
  agent:
    collector:
      grpc:
        server-address: 0.0.0.0:11800

okhttp:
  connectionTimeout: 3000
  readTimeout: 3000

# springdoc-openapi项目配置
springdoc:
  pre-loading-enabled: false
  writer-with-order-by-keys: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'ALL'
      display-name: '全部'
      paths-to-match: '/**'
      packages-to-scan: com.chance.controller
    - group: 'COURSE'
      display-name: '课程'
      paths-to-match: '/**'
      packages-to-scan: com.chance.controller.course
    - group: 'FILE'
      display-name: '文件'
      paths-to-match: '/**'
      packages-to-scan: com.chance.controller.file
    - group: 'TEST'
      display-name: '测试'
      paths-to-match: '/**'
      packages-to-scan: com.chance.controller.test
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-swagger-models: true
    enable-document-manage: true # 是否显示界面中"文档管理"功能
    swagger-model-name: 实体类列表
    enable-version: false
    enable-reload-cache-parameter: false
    enable-after-script: true
    enable-filter-multipart-api-method-type: POST
    enable-filter-multipart-apis: false
    enable-request-cache: true
    enable-host: false # 是否启用Host
    enable-home-custom: false
    home-custom-path: classpath:file/*
    enable-search: false # 是否禁用Ui界面中的搜索框
    enable-footer: false # 是否显示Footer
    #    enable-footer-custom: true # 是否自定义Footer
    #    footer-custom-content: Apache License 2.0 | Copyright  2024-[chance](https://github.com/Chance-Wu/)
    enable-dynamic-parameter: false
    enable-debug: true
    enable-open-api: true # 显示OpenAPI规范
    enable-group: true # 是否开启分组
  cors: false # 是否开启一个默认的 跨域配置,该功能配合自定义Host使用
  production: false # 是否开启生产环境保护策略
  basic:
    enable: false # 是否开启基础认证
    username: chance
    password: 539976
  documents:
    - group: 1
      name: 测试自定义标题分组
      # 某一个文件夹下所有的.md文件
      locations: classpath:markdown/druid/*
    - group: 2
      name: 接口签名
      # 某一个文件夹下单个.md文件
      locations: classpath:markdown/mybatis/*

#rocketmq:
#  name-server: 127.0.0.1:9876
#  consumer:
#    group: GROUP_CHANCE
#    # 一次拉取消息最大值，注意是拉取消息的最大值而非消费最大值
#    pull-batch-size: 10
#  producer:
#    group: GROUP_CHANCE
#    # 发送消息超时时间，默认3000
#    sendMessageTimeout: 10000
#    # 发送消息失败重试次数，默认2
#    retryTimesWhenSendFailed: 2
#    # 异步消息重试此处，默认2
#    retryTimesWhenSendAsyncFailed: 2
#    # 消息最大长度，默认1024 * 1024 * 4(默认4M)
#    maxMessageSize: 4096
#    # 压缩消息阈值，默认4k(1024 * 4)
#    compressMessageBodyThreshold: 4096
#    # 是否在内部发送失败时重试另一个broker，默认false
#    retryNextServer: false

email:
  accounts:
    - name: wuchenyang
      host: mail.heilangroup.cn
      port: 143
      username: wuchenyang@heilangroup.cn
      password: Ww539976
      protocol: imap
#    - name: chance
#      host: imap.163.com
#      port: 993
#      username: clayyoung6@163.com
#      password: MERLMhfxWGNXzLGm
#      protocol: imaps
